receivers:
    otlp:
        protocols:
            grpc:
                endpoint: '0.0.0.0:4317'
            # http:
            #     endpoint: '0.0.0.0:4318'

exporters:
    prometheus:
        endpoint: '0.0.0.0:8889' # changed from 8888 to 8889 to avoid conflict with otel collector's internal metrics port
    otlp/jaeger:
        endpoint: 'jaeger:4317'
        tls:
            insecure: true

service:
    pipelines:
        traces:
            receivers: [otlp]
            exporters: [otlp/jaeger]
        metrics:
            receivers: [otlp]
            exporters: [prometheus]
